const robotActionTypes = {
    CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',
    REQUEST_ROBOTS_START: 'REQUEST_ROBOTS_START',
    REQUEST_ROBOTS_SUCCESS: 'REQUEST_ROBOTS_SUCCESS',
    REQUEST_ROBOTS_FAILED: 'REQUEST_ROBOTS_FAILED',
    SET_ROBOTS: 'SET_ROBOTS'
}

export default robotActionTypes;